## Day 4

### Numpy

*NumPy* (short for Numerical Python)  is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices, along with a large collection of high-level mathematical functions to operate on these arrays.

NumPy is the fundamental package for scientific computing with Python. It contains among other things:

 - a powerful N-dimensional array object

 - sophisticated (broadcasting) functions

 - tools for integrating C/C++ and Fortran code

 - useful linear algebra, Fourier transform, and random number capabilities
 


Why is this useful to astronomers?

Numpy can be used to effectively load, store and manipulate in-memory data in Python. Datasets can come from a wide range of sources and a wide range of formats, including collections of documents, collections of images, collections of sound clips, collections of numerical measurements, or nearly anything else. Despite this apparent heterogeneity, it will help us to think of all data fundamentally as *arrays of numbers*.
For example, images–particularly digital images–can be thought of as simply two-dimensional arrays of numbers representing pixel brightness across the area.

NumPy arrays form the core of nearly the entire ecosystem of data science tools in Python, so time spent learning to use NumPy effectively will be valuable no matter what aspect of data science interests you.

In [1]:
import numpy
numpy.__version__

'1.17.0'

It is a well established convention to import *numpy* in the following way

In [2]:
import numpy as np

In [4]:
np?

### Creating arrays

In [6]:
a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


We passed in a list of numbers. And the output looks like a list. However, unlike *list* objects, *numpy* array elements *must* be of the same type.

In [8]:
print("a is of type ", type(a))
print("The first element of a is of type", type(a[0]))

a is of type  <class 'numpy.ndarray'>
The first element of a is of type <class 'numpy.int64'>


In [10]:
l = [1, 2,3 , 4]
print(type(l[0]))

<class 'int'>


The type of the elements of a *numpy* array is stored in the *dtype* attribute.

In [12]:
print(a.dtype)

int64


What do you think `b.dtype` is below?

In [15]:
b = np.array([1.2, 1, 2, 3])

We can explicitely request the type of array to be created by specifying `dtype`.

In [17]:
c = np.array([1, 2, 3, 4], dtype=np.float32)
print(c)
print(c.dtype)

[1. 2. 3. 4.]
float32


*Numpy* arrays can be multidimensional. One way to create a multidimensional array is to initialize it with a list of lists.

In [20]:
l = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
d = np.array(l)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Other ways to initialize arrays

In [21]:
# Create a length-10 integer array filled with zeros
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [22]:
# Create a 3x5 floating-point array filled with ones
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [23]:
# Create a 3x5 array filled with 3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [24]:
# Create an array filled with a linear sequence
# Starting at 0, ending at 20, stepping by 2
# (this is similar to the built-in range() function)
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [25]:
# Create an array of five values evenly spaced between 0 and 1
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [26]:
# Create a 3x3 array of uniformly distributed
# random values between 0 and 1
np.random.random((3, 3))

array([[0.01395724, 0.0188152 , 0.3355161 ],
       [0.18494303, 0.93902887, 0.14369004],
       [0.45774466, 0.92241057, 0.03414787]])

In [27]:
# Create a 3x3 array of normally distributed random values
# with mean 0 and standard deviation 1
np.random.normal(0, 1, (3, 3))

array([[-0.33568233,  0.05518358, -0.85990665],
       [ 0.26336178, -0.2275811 , -0.76897566],
       [-0.16232824, -1.54488319, -0.3451272 ]])

In [28]:
# Create a 3x3 array of random integers in the interval [0, 10)
np.random.randint(0, 10, (3, 3))

array([[9, 8, 4],
       [4, 2, 1],
       [9, 5, 1]])

In [29]:
# Create a 3x3 identity matrix
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [30]:
# Create an uninitialized array of three integers
# The values will be whatever happens to already exist at that memory location
np.empty(3)

array([1., 1., 1.])

### Basics of Numpy Array

Data manipulation in Python is nearly synonymous with NumPy array manipulation: scientific tools like `astropy` and `pandas` are built around the NumPy array. This section will present several examples of using NumPy array manipulation to access data and subarrays, and to split, reshape, and join the arrays. 


#### Array Attributes

In [31]:
np.random.seed(0)  # seed for reproducibility

x1 = np.random.randint(10, size=6)  # One-dimensional array
x2 = np.random.randint(10, size=(3, 4))  # Two-dimensional array
x3 = np.random.randint(10, size=(3, 4, 5))  # Three-dimensional array

Each array has attributes ndim (the number of dimensions), shape (the size of each dimension), and size (the total size of the array):

In [32]:
print("x3 ndim: ", x3.ndim)
print("x3 shape:", x3.shape)
print("x3 size: ", x3.size)

x3 ndim:  3
x3 shape: (3, 4, 5)
x3 size:  60


#### Array Indexing: Accessing Single Elements

Indexing in NumPy is similar to indexing in Python lists. In a one-dimensional array, the ith value (counting from zero) can be accessed by specifying the desired index in square brackets, just as with Python lists:

In [33]:
x1

array([5, 0, 3, 3, 7, 9])

In [34]:
x1[0]

5

In [35]:
x1[4]

7

To index from the end of the array, you can use negative indices:

In [37]:
x1[-1]

9

In [38]:
x1[-2]

7

In a multi-dimensional array, items can be accessed using a comma-separated tuple of indices:

In [40]:
x2

array([[3, 5, 2, 4],
       [7, 6, 8, 8],
       [1, 6, 7, 7]])

In [42]:
x2[0, 0]

3

In [43]:
x2[2, -1]

7

Values can also be modified using any of the above index notation:

In [44]:
x2[0, 0] = 12
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

#### Array Slicing: Accessing Subarrays

Just as we can use square brackets to access individual array elements, we can also use them to access subarrays with the slice notation, marked by the colon (:) character. The NumPy slicing syntax follows that of the standard Python list; to access a slice of an array x, use this:

`x[start:stop:step]`

If any of these are unspecified, they default to the values start=0, stop=size of dimension, step=1. We'll take a look at accessing sub-arrays in one dimension and in multiple dimensions.

In [48]:
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
x[:5]  # first five elements

array([0, 1, 2, 3, 4])

In [51]:
x[5:]  # elements after index 5

array([5, 6, 7, 8, 9])

In [52]:
x[4:7]  # middle sub-array

array([4, 5, 6])

In [53]:
x[::2]  # every other element

array([0, 2, 4, 6, 8])

In [54]:
x[1::2]  # every other element, starting at index 1

array([1, 3, 5, 7, 9])

In [55]:
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

In [56]:
x2[:2, :3]  # two rows, three columns

array([[12,  5,  2],
       [ 7,  6,  8]])

In [57]:
x2[:3, ::2]  # all rows, every other column

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

Finally, subarray dimensions can even be reversed together:

In [58]:
x2[::-1, ::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

#### Reshaping of Arrays

Another useful type of operation is reshaping of arrays. The most flexible way of doing this is with the reshape method. For example, if you want to put the numbers 1 through 9 in a 3×3 grid, you can do the following:

In [59]:
grid = np.arange(1, 10).reshape((3, 3))
print(grid)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


Note that for this to work, the size of the initial array must match the size of the reshaped array. 

#### Array Concatenation and Splitting

All of the preceding routines worked on single arrays. It's also possible to combine multiple arrays into one, and to conversely split a single array into multiple arrays. We'll take a look at those operations here.

In [60]:
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y])

array([1, 2, 3, 3, 2, 1])

**Exercise:**

Read about and explore *np.dstack*, *np.vstack*, *np.hstack*.

The opposite of concatenation is splitting, which is implemented by the functions np.split, np.hsplit, and np.vsplit. For each of these, we can pass a list of indices giving the split points:

#### Computation on NumPy Arrays: Universal Functions

**Loops are slow**


Let's write a funciton which computes the square values of all elements in an array. Those familiar with languages like *C* nad *Fortran* would find the function below quite natural to write. However, because Python is a dynamically typed language, this type of operation on individual elements is qute slow. 

In [86]:
def compute_squares(values):
    output = np.empty(len(values))
    for i in range(len(values)):
        output[i] = values[i] * values[i]
    return output

Numpy is optimized to perform array (or *vectorized*) operations. This means that instead of performing the square operation on each element of the array, the Numpy interface allows opeartions on the entire array.

Let's do some timings.

In [87]:
values = np.random.randint(1, 100, size=5)

In [88]:
%timeit compute_squares(values)

3.25 µs ± 29.4 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)


In [89]:
%timeit values*values

473 ns ± 8.36 ns per loop (mean ± std. dev. of 7 runs, 1000000 loops each)


In [90]:
from astropy import units as u
((3.24*u.us).to(u.ns))/(466*u.ns)

<Quantity 6.9527897>

**Array arithmetics**

 The standard Python operators for addition, subtraction, multiplication, and division can all be used with Numpy arrays.

In [91]:
x = np.arange(4)
print("x     =", x)
print("x + 5 =", x + 5)
print("x - 5 =", x - 5)
print("x * 2 =", x * 2)
print("x / 2 =", x / 2)
print("x // 2 =", x // 2)  # floor division

x     = [0 1 2 3]
x + 5 = [5 6 7 8]
x - 5 = [-5 -4 -3 -2]
x * 2 = [0 2 4 6]
x / 2 = [0.  0.5 1.  1.5]
x // 2 = [0 0 1 1]


There is also a unary ufunc for negation, and a ** operator for exponentiation, and a % operator for modulus:

In [93]:
print("-x     = ", -x)
print("x ** 2 = ", x ** 2)
print("x % 2  = ", x % 2)

-x     =  [ 0 -1 -2 -3]
x ** 2 =  [0 1 4 9]
x % 2  =  [0 1 0 1]


In addition, these can be strung together however you wish, and the standard order of operations is respected:

In [94]:
-(0.5*x + 1) ** 2

array([-1.  , -2.25, -4.  , -6.25])

**Exercise:**

Numpy provides ufuncs for all trigonometric functions, as well as for exponents and logarithms. Create an array ``x`` and use the trig ufuncs to compute:

```
sin(x)
cos(x)
tan(x)
arcsin(x)
arccos(x)
arctan(x)
exp(x)
log(x)
log10(x)
```

**Statistical functions**